# -*- coding: utf-8 -*-
"""RAG Nestle HR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UuF0QEASlzFvRbMhVqaf6Lhux8hr_8nT

# Install libraries
"""

pip install transformers sentence-transformers langchain langchain_community huggingface_hub

pip install pymupdf chromadb

pip install huggingface_hub

from huggingface_hub import notebook_login
notebook_login()

"""# PDF Reader/ Document Loader"""

import langchain
import langchain_community
from langchain.document_loaders import PyMuPDFLoader

loader = PyMuPDFLoader("the_nestle_hr_policy_pdf_2012.pdf")
documents = loader.load()

print(documents)

doc=documents

len(doc)

doc[2]

"""# Split Text into Chunks"""

from langchain.text_splitter import RecursiveCharacterTextSplitter

text_split = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50,
    separators=["\n\n", "\n", ".", " "]
)

chunks = text_split.split_documents(documents)

print(chunks)

len(chunks)

chunks[5]

"""# Transform sentence/ chunks into embeddings

"""

from langchain_huggingface import HuggingFaceEmbeddings

embedding = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

# from sentence_transformers import SentenceTransformer
# embed_model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")
# embeddings = [embed_model.encode(doc.page_content) for doc in chunks]

"""# Store the embeddings in vector database"""

from langchain.vectorstores import Chroma


# Create Chroma vector store from document chunks
vectorstore = Chroma.from_documents(
    documents=chunks,
    embedding=embedding,
    persist_directory="chroma_db"
)

# Persist to disk
vectorstore.persist()

retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

!pip install -U bitsandbytes accelerate

from langchain.prompts import PromptTemplate

prompt = PromptTemplate(
    input_variables=["context", "question"],
    template="""
Use the following context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer

Context:
{context}

Question:
{question}

Answer:"""
)

from langchain.chains import RetrievalQA
from langchain.llms import HuggingFacePipeline
from transformers import pipeline, AutoModelForCausalLM, BitsAndBytesConfig
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from transformers import AutoModelForSeq2SeqLM
import torch
print(torch.cuda.is_available())
model_id = "mistralai/Mistral-7B-Instruct-v0.3"
# model_id = "google/flan-t5-large"
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    quantization_config=bnb_config,
    torch_dtype=torch.float16
)
# model= AutoModelForSeq2SeqLM.from_pretrained(
#     model_id,
#     device_map="auto",
#     # quantization_config=bnb_config,
#     # torch_dtype=torch.float16
# )
tokenizer = AutoTokenizer.from_pretrained(model_id)

hf_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=1024,
    temperature=0.7,
    top_p=0.95,
    repetition_penalty=1.1,
    do_sample=True
)

llm = HuggingFacePipeline(pipeline=hf_pipeline)

# Build the RAG chain
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    return_source_documents=True,
    chain_type="stuff",
    chain_type_kwargs={"prompt": prompt}
)

# google/flan-t5-base

result = qa_chain.invoke("What are the key findings of the PDF?")
print(result["result"])

result = qa_chain("how can one apply for job at nestle?")
print(result["result"])

# qa_chain = RetrievalQA.from_chain_type(
#     llm=llm,
#     retriever=retriever,
#     return_source_documents=False
# )

result = qa_chain("Jean-Marc Duvoisin, Executive Vice President")
print(result["result"])

"""# Gradio Interface"""

pip install gradio

import gradio as gr

def ask_question(query):
    response = qa_chain.invoke(query)
    return response['result']

demo = gr.Interface(
    fn=ask_question,
    inputs=gr.Textbox(lines=3, placeholder="Ask a question about the document..."),
    outputs="text",
    title="The Nestlé Human Resources Policy",
    theme="default",
)

demo.launch()